name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set cache date
        run: echo "CACHE_DATE=$(date +'%Y-%U')" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      - name: Cache dictionaries
        id: cache-dicts
        uses: actions/cache@v4
        with:
          path: dicts
          key: ${{ runner.os }}-dicts-${{ hashFiles('**/load_dictionary.py') }}-${{ env.CACHE_DATE }}

      - name: Download dictionaries
        if: steps.cache-dicts.outputs.cache-hit != 'true'
        run: |
          python -c "from phone_similarity.g2p.charisu.load_dictionary import load_dictionary_tsv; from phone_similarity.g2p.charisu import LANGUAGE_CODES_CHARSIU as LANGS; [load_dictionary_tsv(l) for l in LANGS]"
      - name: Archive dictionaries
        run: |
          tar -czvf dicts.tar.gz dicts
      - name: Upload assets to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} dicts.tar.gz
